name: Deploy React App

on:
  push:
    branches:
      - master  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20, 22.11.0] # Add multiple Node.js versions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Ensure Correct Permissions on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d "/var/www/react-app/" ]; then
              echo "Directory exists. Fixing permissions..."
            else
              echo "Directory does not exist. Creating..."
              sudo mkdir -p /var/www/react-app/
            fi
            sudo chown -R ubuntu:www-data /var/www/react-app/
            sudo chmod -R 775 /var/www/react-app/

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/"
          target: "/var/www/react-app/"

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
